export const bankNames = [
  "Komerční banka",
  "Česká národní banka",
  "Fio banka",
  "Raiffeisenbank",
  "ČSOB",
  "UniCredit Bank",
  "mBank",
  "Air bank",
  "Max banka",
  "Trinity Bank",
  "MONETA",
  "Oberbank AG",
  "Česká spořitelna",
];
